version: '3'
services:

  mongodb:
    image: "mongo:3.6.3"
    container_name: "mongo"
    hostname: "mongo"
    ports:
      - 27017
    networks:
      - server-mongo

  asanja-server:
    image: "asanja-server"
    ports:
      - 8080:8888
    networks:
      - server-mongo

networks:
  server-mongo:
